### ISSUE TITLE
Will there be any support for file upload ?

### ISSUE THREAD

**Issue by cybergears** [klazbaba/react-native-form-component#68]
I have just started using this lib. It works perfect and saves your from manual work. I was wondering if there will be any file upload component?. It is very much required. 
Thankyou

**Comment by klazbaba** [comment]
Thank you for the nice words @cybergears. For now though, a file upload component is not in view.

> I have just started using this lib. It works perfect and saves your from manual work. I was wondering if there will be any file upload component?. It is very much required. Thankyou
