### ISSUE TITLE
Change red border on error

### ISSUE THREAD

**Issue by radekzz** [klazbaba/react-native-form-component#70]
Hi,
ho can i change red border on error? 

I see it creates a wrapper around FormItem, which is not very helpful. It would be nice to have these styles as a parameter.
```
React.createElement(View, {
    style: [styles.wrapper, props.textArea ? {
      height: 120
    } : undefined, props.style, hasError.status ? {
      borderColor: colors.red,
      borderWidth: 1
    } : undefined]
```

**Comment by klazbaba** [comment]
> Hi, ho can i change red border on error?
> 
> I see it creates a wrapper around FormItem, which is not very helpful. It would be nice to have these styles as a parameter.
> 
> ```
> React.createElement(View, {
>     style: [styles.wrapper, props.textArea ? {
>       height: 120
>     } : undefined, props.style, hasError.status ? {
>       borderColor: colors.red,
>       borderWidth: 1
>     } : undefined]
> ```

Could you please make a pr for this?

**Comment by klazbaba** [comment]
@radekzz this is now possible with version 2.3.1.
