### ISSUE TITLE
buttonStyle ??

### ISSUE THREAD

**Issue by Denver-sn** [klazbaba/react-native-form-component#80]
is there any doc of how to customize it ?

**Comment by klazbaba** [comment]
What do you mean by customize?

**Comment by klazbaba** [comment]
> is there any doc of how to customize it ?

What do you mean by customize?

**Comment by Denver-sn** [comment]
> > is there any doc of how to customize it ?
> 
> What do you mean by customize?
> 
> If for example you want to change the button's background color, you can do
> 
> ```
> <Form  buttonStyle={{backgroundColor: 'green'}}>
>     <FormItem />
>   </Form>
> ```

yeah that's exactly what i need, thanks !
