### ISSUE TITLE
Problem with props autoFocus in PinInput

### ISSUE THREAD

**Issue by nkqdev** [klazbaba/react-native-form-component#97]
When i'm set autoFocus to true it automatically choose the last character of the pin code which i expected is the first character
Here is my code:
`<PinInput
     numOfInput={pinLength}
     placeholder="-"
     placeholderTextColor={'gray'}
     onChangeText={text => setPin(text)}
     autoFocus={true}
     keyboardType="number-pad"
/>`

**Comment by klazbaba** [comment]
> When i'm set autoFocus to true it automatically choose the last character of the pin code which i expected is the first character Here is my code: `<PinInput numOfInput={pinLength} placeholder="-" placeholderTextColor={'gray'} onChangeText={text => setPin(text)} autoFocus={true} keyboardType="number-pad" />`

Thanks for reporting. Will look into this.

**Comment by klazbaba** [comment]
> > When i'm set autoFocus to true it automatically choose the last character of the pin code which i expected is the first character Here is my code: `<PinInput numOfInput={pinLength} placeholder="-" placeholderTextColor={'gray'} onChangeText={text => setPin(text)} autoFocus={true} keyboardType="number-pad" />`
> 
> Thanks for reporting. Will look into this.

This issue has been resolved in v2.6.13. So I shall be closing this issue now.

**Comment by nkqdev** [comment]
> > > When i'm set autoFocus to true it automatically choose the last character of the pin code which i expected is the first character Here is my code: `<PinInput numOfInput={pinLength} placeholder="-" placeholderTextColor={'gray'} onChangeText={text => setPin(text)} autoFocus={true} keyboardType="number-pad" />`
> > 
> > 
> > Thanks for reporting. Will look into this.
> 
> This issue has been resolved in v2.6.13. So I shall be closing this issue now.

Thank you!
